# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL: https://jatinsanghvi.github.io/
defaultContentLanguage: en

enableRobotsTXT: true

pagination:
  pagerSize: 10

summaryLength: 0

frontmatter:
  date:
    - :filename # Pick the date from filename.

outputs:
  home:
    - HTML
    - RSS
    - JSON
